"""core schema

Core data model from SADD Figure 2.5 plus audit_log (Figure 2.6), and the
administrator-configurable parameter defaults from SRS Table 4.0-B.

Revision ID: 0001
Revises:
Create Date: 2026-10-05 15:12:49.838434

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("actor_id", sa.String(length=64), nullable=True),
        sa.Column("actor_role", sa.String(length=20), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("entity_type", sa.String(length=64), nullable=False),
        sa.Column("entity_id", sa.String(length=64), nullable=True),
        sa.Column("before", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("after", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("correlation_id", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    op.create_table(
        "discount_rules",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.Column("end_time", sa.Time(), nullable=False),
        sa.Column("pct", sa.Integer(), nullable=False),
        sa.Column(
            "scope", sa.Enum("ALL", "CATEGORY", "ITEMS", name="discount_scope"), nullable=False
        ),
        sa.Column(
            "category",
            sa.Enum("MEAL", "SNACK", "BEVERAGE", "DESSERT", name="item_category"),
            nullable=True,
        ),
        sa.Column("active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("pct BETWEEN 1 AND 50", name=op.f("ck_discount_rules_pct_range")),
        sa.CheckConstraint("start_time < end_time", name=op.f("ck_discount_rules_time_order")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_discount_rules")),
    )
    op.create_table(
        "menu_items",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.String(length=60), nullable=False),
        sa.Column("description", sa.String(length=300), server_default="", nullable=False),
        sa.Column(
            "category",
            sa.Enum("MEAL", "SNACK", "BEVERAGE", "DESSERT", name="item_category"),
            nullable=False,
        ),
        sa.Column("price_paise", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "REMOVED", name="item_status"),
            server_default="ACTIVE",
            nullable=False,
        ),
        sa.Column("unavailable", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("unavailable_reason", sa.Text(), nullable=True),
        sa.Column("unavailable_source", sa.String(length=20), nullable=True),
        sa.Column("unavailable_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "price_paise BETWEEN 100 AND 50000", name=op.f("ck_menu_items_price_range")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_menu_items")),
    )
    op.create_index(
        "uq_menu_items_active_name",
        "menu_items",
        [sa.literal_column("lower(name)")],
        unique=True,
        postgresql_where=sa.text("status = 'ACTIVE'"),
    )
    op.create_table(
        "rate_limits",
        sa.Column("subject", sa.String(length=200), nullable=False),
        sa.Column("window_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("count", sa.Integer(), server_default="0", nullable=False),
        sa.PrimaryKeyConstraint("subject", "window_start", name=op.f("pk_rate_limits")),
    )
    op.create_table(
        "service_days",
        sa.Column("service_date", sa.Date(), nullable=False),
        sa.Column("window_start", sa.Time(), nullable=False),
        sa.Column("window_end", sa.Time(), nullable=False),
        sa.Column("slot_len_min", sa.Integer(), nullable=False),
        sa.Column("default_capacity", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "default_capacity BETWEEN 1 AND 100", name=op.f("ck_service_days_capacity_range")
        ),
        sa.CheckConstraint("slot_len_min > 0", name=op.f("ck_service_days_slot_len_positive")),
        sa.CheckConstraint("window_start < window_end", name=op.f("ck_service_days_window_order")),
        sa.PrimaryKeyConstraint("service_date", name=op.f("pk_service_days")),
    )
    op.create_table(
        "settings",
        sa.Column("key", sa.String(length=50), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_settings")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("role", sa.Enum("STUDENT", "KITCHEN", "ADMIN", name="user_role"), nullable=False),
        sa.Column("subsidy_eligible", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "daily_inventory",
        sa.Column("item_id", sa.UUID(), nullable=False),
        sa.Column("service_date", sa.Date(), nullable=False),
        sa.Column("total", sa.Integer(), nullable=False),
        sa.Column("allocated", sa.Integer(), server_default="0", nullable=False),
        sa.CheckConstraint(
            "0 <= allocated AND allocated <= total",
            name=op.f("ck_daily_inventory_allocated_within_total"),
        ),
        sa.CheckConstraint("total BETWEEN 0 AND 500", name=op.f("ck_daily_inventory_total_range")),
        sa.ForeignKeyConstraint(
            ["item_id"], ["menu_items.id"], name=op.f("fk_daily_inventory_item_id_menu_items")
        ),
        sa.ForeignKeyConstraint(
            ["service_date"],
            ["service_days.service_date"],
            name=op.f("fk_daily_inventory_service_date_service_days"),
        ),
        sa.PrimaryKeyConstraint("item_id", "service_date", name=op.f("pk_daily_inventory")),
    )
    op.create_table(
        "discount_rule_items",
        sa.Column("rule_id", sa.UUID(), nullable=False),
        sa.Column("item_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["item_id"], ["menu_items.id"], name=op.f("fk_discount_rule_items_item_id_menu_items")
        ),
        sa.ForeignKeyConstraint(
            ["rule_id"],
            ["discount_rules.id"],
            name=op.f("fk_discount_rule_items_rule_id_discount_rules"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("rule_id", "item_id", name=op.f("pk_discount_rule_items")),
    )
    op.create_table(
        "idempotency_keys",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("request_hash", sa.Text(), nullable=False),
        sa.Column(
            "state", sa.Enum("IN_PROGRESS", "COMPLETED", name="idempotency_state"), nullable=False
        ),
        sa.Column("response", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_idempotency_keys_user_id_users")
        ),
        sa.PrimaryKeyConstraint("user_id", "key", name=op.f("pk_idempotency_keys")),
    )
    op.create_index(
        op.f("ix_idempotency_keys_created_at"), "idempotency_keys", ["created_at"], unique=False
    )
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("replaced_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_refresh_tokens_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_tokens")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_refresh_tokens_token_hash")),
    )
    op.create_index(op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False)
    op.create_table(
        "slots",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("service_date", sa.Date(), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("capacity", sa.Integer(), nullable=False),
        sa.Column("booked", sa.Integer(), server_default="0", nullable=False),
        sa.CheckConstraint(
            "0 <= booked AND booked <= capacity", name=op.f("ck_slots_booked_within_capacity")
        ),
        sa.CheckConstraint("starts_at < ends_at", name=op.f("ck_slots_time_order")),
        sa.ForeignKeyConstraint(
            ["service_date"],
            ["service_days.service_date"],
            name=op.f("fk_slots_service_date_service_days"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_slots")),
        sa.UniqueConstraint("service_date", "starts_at", name="uq_slots_service_date_starts_at"),
    )
    op.create_index(op.f("ix_slots_service_date"), "slots", ["service_date"], unique=False)
    op.create_table(
        "orders",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("student_id", sa.UUID(), nullable=False),
        sa.Column("slot_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING_PAYMENT",
                "ACCEPTED",
                "PREPARING",
                "READY",
                "PICKED_UP",
                "NO_SHOW",
                "CANCELLED",
                "PAYMENT_FAILED",
                name="order_status",
            ),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("paid_paise", sa.Integer(), server_default="0", nullable=False),
        sa.Column("subsidy_applied", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("paid_paise >= 0", name=op.f("ck_orders_paid_non_negative")),
        sa.ForeignKeyConstraint(["slot_id"], ["slots.id"], name=op.f("fk_orders_slot_id_slots")),
        sa.ForeignKeyConstraint(
            ["student_id"], ["users.id"], name=op.f("fk_orders_student_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orders")),
    )
    op.create_index(op.f("ix_orders_slot_id"), "orders", ["slot_id"], unique=False)
    op.create_index(op.f("ix_orders_status"), "orders", ["status"], unique=False)
    op.create_index(op.f("ix_orders_student_id"), "orders", ["student_id"], unique=False)
    op.create_table(
        "order_lines",
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("item_id", sa.UUID(), nullable=False),
        sa.Column("qty", sa.Integer(), nullable=False),
        sa.CheckConstraint("qty >= 1", name=op.f("ck_order_lines_qty_positive")),
        sa.ForeignKeyConstraint(
            ["item_id"], ["menu_items.id"], name=op.f("fk_order_lines_item_id_menu_items")
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_order_lines_order_id_orders"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("order_id", "item_id", name=op.f("pk_order_lines")),
    )
    op.create_table(
        "order_modifications",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("HOLDING", "APPLIED", "RELEASED", name="modification_status"),
            nullable=False,
        ),
        sa.Column("new_slot_id", sa.UUID(), nullable=True),
        sa.Column("new_lines", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("diff_paise", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["new_slot_id"], ["slots.id"], name=op.f("fk_order_modifications_new_slot_id_slots")
        ),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_order_modifications_order_id_orders")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_modifications")),
    )
    op.create_index(
        op.f("ix_order_modifications_order_id"), "order_modifications", ["order_id"], unique=False
    )
    op.create_table(
        "order_transitions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column(
            "from",
            sa.Enum(
                "PENDING_PAYMENT",
                "ACCEPTED",
                "PREPARING",
                "READY",
                "PICKED_UP",
                "NO_SHOW",
                "CANCELLED",
                "PAYMENT_FAILED",
                name="order_status",
            ),
            nullable=True,
        ),
        sa.Column(
            "to",
            sa.Enum(
                "PENDING_PAYMENT",
                "ACCEPTED",
                "PREPARING",
                "READY",
                "PICKED_UP",
                "NO_SHOW",
                "CANCELLED",
                "PAYMENT_FAILED",
                name="order_status",
            ),
            nullable=False,
        ),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column(
            "actor_role", sa.Enum("STUDENT", "KITCHEN", "ADMIN", name="user_role"), nullable=True
        ),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column(
            "at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_order_transitions_order_id_orders")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_transitions")),
    )
    op.create_index(
        op.f("ix_order_transitions_order_id"), "order_transitions", ["order_id"], unique=False
    )
    op.create_table(
        "price_snapshots",
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("breakdown", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("payable_paise", sa.Integer(), nullable=False),
        sa.Column(
            "priced_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_price_snapshots_order_id_orders")
        ),
        sa.PrimaryKeyConstraint("order_id", "version", name=op.f("pk_price_snapshots")),
    )
    op.create_table(
        "payments",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("modification_id", sa.UUID(), nullable=True),
        sa.Column("kind", sa.Enum("AUTH", "VOID", "REFUND", name="payment_kind"), nullable=False),
        sa.Column(
            "cause",
            sa.Enum("CREATE", "MODIFY", "CANCEL", "EXPIRY", name="payment_cause"),
            nullable=False,
        ),
        sa.Column("amount_paise", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "SUCCEEDED", "FAILED", name="payment_status"),
            server_default="PENDING",
            nullable=False,
        ),
        sa.Column("provider_ref", sa.String(length=100), nullable=True),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("amount_paise >= 0", name=op.f("ck_payments_amount_non_negative")),
        sa.ForeignKeyConstraint(
            ["modification_id"],
            ["order_modifications.id"],
            name=op.f("fk_payments_modification_id_order_modifications"),
        ),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_payments_order_id_orders")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payments")),
    )
    op.create_index(op.f("ix_payments_order_id"), "payments", ["order_id"], unique=False)
    op.create_index(
        "uq_payments_cancel_refund",
        "payments",
        ["order_id"],
        unique=True,
        postgresql_where=sa.text("kind = 'REFUND' AND cause = 'CANCEL'"),
    )
    op.create_index(
        "uq_payments_modify_refund",
        "payments",
        ["modification_id"],
        unique=True,
        postgresql_where=sa.text("kind = 'REFUND' AND cause = 'MODIFY'"),
    )
    # ### end Alembic commands ###

    settings = sa.table(
        "settings",
        sa.column("key", sa.String),
        sa.column("value", postgresql.JSONB),
    )
    op.bulk_insert(
        settings,
        [{"key": key, "value": value} for key, value in PARAMETER_DEFAULTS.items()],
    )


# Administrator-configurable parameters, SRS Table 4.0-B. Deploy-time parameters
# (P-PAY_TIMEOUT, P-HOLD_EXPIRY, ...) come from environment variables instead.
PARAMETER_DEFAULTS = {
    "P-SLOT_LEN_MIN": 15,
    "P-MENU_OPEN": "08:00",
    "P-BOOK_CLOSE_MIN": 15,
    "P-CUTOFF_MIN": 10,
    "P-AUTO_PREP_MIN": 10,
    "P-NOSHOW_GRACE_MIN": 15,
    "P-LATE_REFUND_PCT": 50,
    "P-MAX_QTY": 3,
    "P-MAX_ACTIVE": 2,
    "P-SUBSIDY_AMT_PAISE": 2000,
    "P-SUBSIDY_CAP_PCT": 50,
    "P-AGENT_LEAD_MIN": 30,
    "P-REPL_MAX": 200,
}

ENUM_TYPES = (
    "user_role",
    "item_category",
    "item_status",
    "discount_scope",
    "order_status",
    "modification_status",
    "payment_kind",
    "payment_cause",
    "payment_status",
    "idempotency_state",
)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_payments_modify_refund",
        table_name="payments",
        postgresql_where=sa.text("kind = 'REFUND' AND cause = 'MODIFY'"),
    )
    op.drop_index(
        "uq_payments_cancel_refund",
        table_name="payments",
        postgresql_where=sa.text("kind = 'REFUND' AND cause = 'CANCEL'"),
    )
    op.drop_index(op.f("ix_payments_order_id"), table_name="payments")
    op.drop_table("payments")
    op.drop_table("price_snapshots")
    op.drop_index(op.f("ix_order_transitions_order_id"), table_name="order_transitions")
    op.drop_table("order_transitions")
    op.drop_index(op.f("ix_order_modifications_order_id"), table_name="order_modifications")
    op.drop_table("order_modifications")
    op.drop_table("order_lines")
    op.drop_index(op.f("ix_orders_student_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_status"), table_name="orders")
    op.drop_index(op.f("ix_orders_slot_id"), table_name="orders")
    op.drop_table("orders")
    op.drop_index(op.f("ix_slots_service_date"), table_name="slots")
    op.drop_table("slots")
    op.drop_index(op.f("ix_refresh_tokens_user_id"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index(op.f("ix_idempotency_keys_created_at"), table_name="idempotency_keys")
    op.drop_table("idempotency_keys")
    op.drop_table("discount_rule_items")
    op.drop_table("daily_inventory")
    op.drop_table("users")
    op.drop_table("settings")
    op.drop_table("service_days")
    op.drop_table("rate_limits")
    op.drop_index(
        "uq_menu_items_active_name",
        table_name="menu_items",
        postgresql_where=sa.text("status = 'ACTIVE'"),
    )
    op.drop_table("menu_items")
    op.drop_table("discount_rules")
    op.drop_table("audit_log")
    # ### end Alembic commands ###
    for enum_type in ENUM_TYPES:
        op.execute(f"DROP TYPE IF EXISTS {enum_type}")
